### ISSUE TITLE
After toggling Tasks map highlight layer on, it sits above and stops selection of Route lines and Issue records

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#57]
First noticed in CAMS Mobile v4.3.10 - don't know if this was present in previous versions or not. This can be reproduced by the following:

1. Go to the map and find a Route record with an assigned Task (i.e. a yellow-background-highlighted Route line on the map)
2. Go to the map layer control window
3. Turn Tasks layer off
4. Go back to the map
5. Turn Tasks layer on
6. Go back to the map
7. You'll see at this stage that the yellow Task highlight will be above the Route line and stopping you selecting the Route record

You can work around this by turning the Route map layer off and on again which brings the Route layer back to the top and reinstates the selection ability, but obviously the above is a bug.

Desired outcome is to make sure the Tasks layer, when turned on, is always at the bottom of the map layers and not stopping selection of any other records

**Comment by am-esdm** [comment]
The task layer sitting above other layers also seems to affect Assigned Issues that have associated Tasks. This second problem seems to have the same route cause as this original reported problem. This behaviour can be replicated by using a CAMS Mobile test sync account that has some Assigned Issues as Tasks (e.g. see 'xgEastSus'), then viewing each of the Issues on the map from the Tasks list - at least some of these Issue records will suffer from the Tasks map layer highlight overlaying the Issues layer features, so you can't select the Issues (weirdly sometimes (and this is changeable!) a few of the Issue records sit above the Tasks layer and you can select them)

**Comment by LaineS** [comment]
Fixed in v4.4.1

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.1
**CAMS Mobile sync account**: xgWCP
**Details:** Have found intermittent instances of the same problem still affecting the Issues layer, i.e. the Tasks layers sits above it and stops interaction with the Issues layer. It doesn't happen upon initial app startup and map view for the first few Tasks-related records, but if you interact with the data for approx. 5 mins, viewing a range of assigned task Routes and Issues and flicking back and forth between the tasks window, map window and layer control window (e.g. toggling the Tasks layer on and off), the Tasks layer suddenly sits above some Issue records on the map and stops you interacting with them - haven't found an exact pattern to replicate this yet

**Comment by LaineS** [comment]
Ready to test in v4.4.2

**Comment by KathrynSteemson** [comment]
Device: Samsung Galaxy Tab A
OS Version: Android v5.1.1
App Version: v4.4.2
CAMS Mobile sync account: xgStaffs
Details: Not able to replicate any problems with selecting issues highlighted as tasks. Could always make a selection.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.2
**Sync Account**: xgDev
**Status**: Pass
**Details**: Tested with assigning new issues from CAMS Desktop, including Line & Polygon features. Able to select assigned issues after toggling tasks layer on and off.
