### ISSUE TITLE
Completed Jobs incorrectly showing in the app

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#82]
First identified during testing of CAMS Mobile v4.3.12: Completed Job records are displaying in the app, they should not be (this applies to both Jobs associated with standalone Issues on Link records and Land records, as well as Jobs associated with Issues on Furniture records)

**Comment by LaineS** [comment]
I think this might be an API issue - can you get it to only return incomplete jobs? Does this fix the issue?

**Comment by LaineS** [comment]
Fixed, the app now does not show completed jobs

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 10
**App Version**: 4.5.5
**Sync Account**: xgdev
**Status**: Fail
**Details**: Updated job to completed. Synchronised data. Completed job still shows.
![CompleteJob](https://user-images.githubusercontent.com/25226464/192822241-ad85c094-09d3-4f42-a3c1-e97af0726a4a.png)

For reference, the job is on this issue
![Location](https://user-images.githubusercontent.com/25226464/192822399-ba522a2c-1c0b-4d1b-83d7-4ae06cdebc7c.png)

Cleared all data and re-sync'd. Job still shows.

**Comment by Timothy-D** [comment]
**Device**: Emulator
**OS Version**: Android 10
**App Version**:4.5.6
**Sync Account**: xgdev
**Status**: Pass
**Details**: Completed jobs not showing

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 3
**OS Version**: Android 10
**App Version**: 4.5.6
**Sync Account**: xgDev
**Status**: Pass
